import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";


import {
  Poppins as fontPoppins,
  Montserrat as fontMontserrat
} from '@next/font/google';


const inter = Inter({ subsets: ["latin"] });
const roboto_gas = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

const poppins = fontPoppins({
    weight: ['400', '700'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-poppins',
});

const montserrat = fontMontserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className} style={{left: "0px", right: "0px", top : "0px", position: "absolute",bottom: "0px"}}>{children}</body>
    </html>
  );
}
